language: java
jdk:
- openjdk8

before_install: chmod +x gradlew
install: "./gradlew setupCIWorkspace -s"
script: "./gradlew build -s"

deploy:
  provider: releases
  api_key:
    secure: <key>
  overwrite: true
  file_glob: true
  file: "build/libs/*"
  skip_cleanup: true
  on:
    repo: Pxl-8/<repo>
    tags: true